### ISSUE TITLE
x509 cert conversion is failing

### ISSUE THREAD

**Issue by thiru-chidambaram** [thiru-chidambaram/enterpriseXTLVParser#4]

**Comment by thiru-chidambaram** [comment]
java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:110)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at com.enterprisex.TLVReader.parseBody(TLVReader.java:106)
	at com.enterprisex.TLVParser.main(TLVParser.java:24)
Caused by: java.io.IOException: Empty input
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:106)
	... 3 more

**Comment by thiru-chidambaram** [comment]
Fixed

**Comment by siddarambali** [comment]
Hi, can u plz let me know how u resolved this? I am also hitting this issue in my project.
