### ISSUE TITLE
Exception while reading last record

### ISSUE THREAD

**Issue by thiru-chidambaram** [thiru-chidambaram/enterpriseXTLVParser#5]
While reading the last record, the parser is basically going out of bounds. Have to check whether the endIndex is calculated wrongly.

**Comment by thiru-chidambaram** [comment]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.enterprisex.TLVReader.parseBody(TLVReader.java:103)
	at com.enterprisex.TLVParser.main(TLVParser.java:24)

**Comment by thiru-chidambaram** [comment]
Fixed.
